import { config } from 'dotenv';
config();

import '@/ai/flows/generate-visual-media.ts';
import '@/ai/flows/analyze-user-input.ts';
import '@/ai/flows/enable-voice-input.ts';
import '@/ai/flows/collaborative-ai-assistance.ts';
import '@/ai/flows/generate-character.ts';
import '@/ai/flows/generate-audio.ts';
import '@/ai/flows/voice-biometrics.ts';
import '@/ai/flows/create-copilot-session.ts';
import '@/ai/flows/list-copilot-sessions.ts';
import '@/ai/flows/get-copilot-session.ts';
import '@/ai/flows/update-copilot-session.ts';
import '@/ai/flows/create-session.ts';
import '@/ai/flows/add-participant-to-session.ts';
import '@/ai/flows/get-session-messages.ts';
import '@/ai/flows/get-session-participants.ts';
import '@/ai/flows/remove-participant-from-session.ts';
import '@/ai/flows/save-message-to-session.ts';
import '@/ai/flows/list-sessions.ts';
import '@/ai/flows/get-user-by-username.ts';
import '@/ai/flows/voice-biometrics.ts';
